platform :ios, '14.1'
use_frameworks!

def swinject
  # DI: Swinject
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'Swinject'
end

def iosapp_shared
  # KMM shared library
  pod 'shared', :path => '../shared'
end


# TARGETS

target 'iosApp' do
  swinject
  iosapp_shared
end
