name: Kmplate build # Replace name with your own project name here

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: iosSimulatorArm64Test
            os: macos-latest
          - target: testReleaseUnitTest
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up Java JDK ${{ vars.JAVA_JDK_VERSION }}"
        uses: actions/setup-java@v4
        with:
          java-version: '${{ vars.JAVA_JDK_VERSION }}'
          distribution: "zulu"

      - name: Setup Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: ${{ matrix.target }}

  notify:
    needs: build
    uses: ./.github/workflows/notify.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
