name: Notify build status on Slack

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification on Slack
        uses: rtCamp/action-slack-notify@v2.2.0
        if: ${{ success() }}
        env:
          SLACK_CHANNEL: ${{ vars.SLACK_GITHUB_ACTIONS_CHANNEL_NAME }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: ${{ vars.SLACK_GITHUB_ACTIONS_ICON_URL }}
          SLACK_MESSAGE: ':white_check_mark: Build successful! :rocket:'
          SLACK_TITLE: Kmplate build status
          SLACK_USERNAME: Github Actions CI
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send notification on Slack
        uses: rtCamp/action-slack-notify@v2.2.0
        if: ${{ failure() }}
        env:
          SLACK_CHANNEL: ${{ vars.SLACK_GITHUB_ACTIONS_CHANNEL_NAME }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: ${{ vars.SLACK_GITHUB_ACTIONS_ICON_URL }}
          SLACK_MESSAGE: ':x: Build failed! :pensive:'
          SLACK_TITLE: Kmplate build status
          SLACK_USERNAME: Github Actions CI
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
